<?xml version="1.0" encoding="utf-8"?><Database Name="JPStarter" Class="LINQtoSQLlandingpgDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=athena;Initial Catalog=JPStarter;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="JPStarterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vw_FilesNotYetLoaded" Member="vw_FilesNotYetLoadeds">
    <Type Name="vw_FilesNotYetLoaded">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="filename" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="filetype" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="staging.LandingPages" Member="stagingLandingPages">
    <Type Name="stagingLandingPage">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LandingPage" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Sessions" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SessionRate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NewUsers" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BounceRate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PagesSession" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AvgSessionDuration" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Transactions" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Revenue" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EcommerceConversionRate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoadedFile_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>