#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandingPagesMVC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JPStarter")]
	public partial class LINQtoSQLlandingpgDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLandingPagestaging(LandingPagestaging instance);
    partial void UpdateLandingPagestaging(LandingPagestaging instance);
    partial void DeleteLandingPagestaging(LandingPagestaging instance);
    partial void InsertLoadedFile(LoadedFile instance);
    partial void UpdateLoadedFile(LoadedFile instance);
    partial void DeleteLoadedFile(LoadedFile instance);
    #endregion
		
		public LINQtoSQLlandingpgDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["JPStarterConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLlandingpgDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLlandingpgDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLlandingpgDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLlandingpgDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LandingPagestaging> LandingPagestagings
		{
			get
			{
				return this.GetTable<LandingPagestaging>();
			}
		}
		
		public System.Data.Linq.Table<LoadedFile> LoadedFiles
		{
			get
			{
				return this.GetTable<LoadedFile>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="staging.LandingPages")]
	public partial class LandingPagestaging : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _LandingPage1;
		
		private string _Sessions;
		
		private string _SessionRate;
		
		private string _NewUsers;
		
		private string _BounceRate;
		
		private string _PagesSession;
		
		private string _AvgSessionDuration;
		
		private string _Transactions;
		
		private string _Revenue;
		
		private string _EcommerceConversionRate;
		
		private System.Nullable<int> _LoadedFile_id;
		
		private EntityRef<LoadedFile> _LoadedFile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnLandingPageChanging(string value);
    partial void OnLandingPageChanged();
    partial void OnSessionsChanging(string value);
    partial void OnSessionsChanged();
    partial void OnSessionRateChanging(string value);
    partial void OnSessionRateChanged();
    partial void OnNewUsersChanging(string value);
    partial void OnNewUsersChanged();
    partial void OnBounceRateChanging(string value);
    partial void OnBounceRateChanged();
    partial void OnPagesSessionChanging(string value);
    partial void OnPagesSessionChanged();
    partial void OnAvgSessionDurationChanging(string value);
    partial void OnAvgSessionDurationChanged();
    partial void OnTransactionsChanging(string value);
    partial void OnTransactionsChanged();
    partial void OnRevenueChanging(string value);
    partial void OnRevenueChanged();
    partial void OnEcommerceConversionRateChanging(string value);
    partial void OnEcommerceConversionRateChanged();
    partial void OnLoadedFile_idChanging(System.Nullable<int> value);
    partial void OnLoadedFile_idChanged();
    #endregion
		
		public LandingPagestaging()
		{
			this._LoadedFile = default(EntityRef<LoadedFile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandingPage1", DbType="VarChar(8000)")]
		public string LandingPage
		{
			get
			{
				return this._LandingPage1;
			}
			set
			{
				if ((this._LandingPage1 != value))
				{
					this.OnLandingPageChanging(value);
					this.SendPropertyChanging();
					this._LandingPage1 = value;
					this.SendPropertyChanged("LandingPage");
					this.OnLandingPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sessions", DbType="VarChar(50)")]
		public string Sessions
		{
			get
			{
				return this._Sessions;
			}
			set
			{
				if ((this._Sessions != value))
				{
					this.OnSessionsChanging(value);
					this.SendPropertyChanging();
					this._Sessions = value;
					this.SendPropertyChanged("Sessions");
					this.OnSessionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionRate", DbType="VarChar(50)")]
		public string SessionRate
		{
			get
			{
				return this._SessionRate;
			}
			set
			{
				if ((this._SessionRate != value))
				{
					this.OnSessionRateChanging(value);
					this.SendPropertyChanging();
					this._SessionRate = value;
					this.SendPropertyChanged("SessionRate");
					this.OnSessionRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewUsers", DbType="VarChar(50)")]
		public string NewUsers
		{
			get
			{
				return this._NewUsers;
			}
			set
			{
				if ((this._NewUsers != value))
				{
					this.OnNewUsersChanging(value);
					this.SendPropertyChanging();
					this._NewUsers = value;
					this.SendPropertyChanged("NewUsers");
					this.OnNewUsersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BounceRate", DbType="VarChar(50)")]
		public string BounceRate
		{
			get
			{
				return this._BounceRate;
			}
			set
			{
				if ((this._BounceRate != value))
				{
					this.OnBounceRateChanging(value);
					this.SendPropertyChanging();
					this._BounceRate = value;
					this.SendPropertyChanged("BounceRate");
					this.OnBounceRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagesSession", DbType="VarChar(50)")]
		public string PagesSession
		{
			get
			{
				return this._PagesSession;
			}
			set
			{
				if ((this._PagesSession != value))
				{
					this.OnPagesSessionChanging(value);
					this.SendPropertyChanging();
					this._PagesSession = value;
					this.SendPropertyChanged("PagesSession");
					this.OnPagesSessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgSessionDuration", DbType="VarChar(50)")]
		public string AvgSessionDuration
		{
			get
			{
				return this._AvgSessionDuration;
			}
			set
			{
				if ((this._AvgSessionDuration != value))
				{
					this.OnAvgSessionDurationChanging(value);
					this.SendPropertyChanging();
					this._AvgSessionDuration = value;
					this.SendPropertyChanged("AvgSessionDuration");
					this.OnAvgSessionDurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transactions", DbType="VarChar(50)")]
		public string Transactions
		{
			get
			{
				return this._Transactions;
			}
			set
			{
				if ((this._Transactions != value))
				{
					this.OnTransactionsChanging(value);
					this.SendPropertyChanging();
					this._Transactions = value;
					this.SendPropertyChanged("Transactions");
					this.OnTransactionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Revenue", DbType="VarChar(50)")]
		public string Revenue
		{
			get
			{
				return this._Revenue;
			}
			set
			{
				if ((this._Revenue != value))
				{
					this.OnRevenueChanging(value);
					this.SendPropertyChanging();
					this._Revenue = value;
					this.SendPropertyChanged("Revenue");
					this.OnRevenueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EcommerceConversionRate", DbType="VarChar(50)")]
		public string EcommerceConversionRate
		{
			get
			{
				return this._EcommerceConversionRate;
			}
			set
			{
				if ((this._EcommerceConversionRate != value))
				{
					this.OnEcommerceConversionRateChanging(value);
					this.SendPropertyChanging();
					this._EcommerceConversionRate = value;
					this.SendPropertyChanged("EcommerceConversionRate");
					this.OnEcommerceConversionRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadedFile_id", DbType="Int")]
		public System.Nullable<int> LoadedFile_id
		{
			get
			{
				return this._LoadedFile_id;
			}
			set
			{
				if ((this._LoadedFile_id != value))
				{
					if (this._LoadedFile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoadedFile_idChanging(value);
					this.SendPropertyChanging();
					this._LoadedFile_id = value;
					this.SendPropertyChanged("LoadedFile_id");
					this.OnLoadedFile_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoadedFile_LandingPagestaging", Storage="_LoadedFile", ThisKey="LoadedFile_id", OtherKey="id", IsForeignKey=true)]
		public LoadedFile LoadedFile
		{
			get
			{
				return this._LoadedFile.Entity;
			}
			set
			{
				LoadedFile previousValue = this._LoadedFile.Entity;
				if (((previousValue != value) 
							|| (this._LoadedFile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoadedFile.Entity = null;
						previousValue.LandingPagestagings.Remove(this);
					}
					this._LoadedFile.Entity = value;
					if ((value != null))
					{
						value.LandingPagestagings.Add(this);
						this._LoadedFile_id = value.id;
					}
					else
					{
						this._LoadedFile_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoadedFile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoadedFiles")]
	public partial class LoadedFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _filename;
		
		private string _filetype;
		
		private EntitySet<LandingPagestaging> _LandingPagestagings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    partial void OnfiletypeChanging(string value);
    partial void OnfiletypeChanged();
    #endregion
		
		public LoadedFile()
		{
			this._LandingPagestagings = new EntitySet<LandingPagestaging>(new Action<LandingPagestaging>(this.attach_LandingPagestagings), new Action<LandingPagestaging>(this.detach_LandingPagestagings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="VarChar(1000)")]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this.OnfilenameChanging(value);
					this.SendPropertyChanging();
					this._filename = value;
					this.SendPropertyChanged("filename");
					this.OnfilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filetype", DbType="VarChar(255)")]
		public string filetype
		{
			get
			{
				return this._filetype;
			}
			set
			{
				if ((this._filetype != value))
				{
					this.OnfiletypeChanging(value);
					this.SendPropertyChanging();
					this._filetype = value;
					this.SendPropertyChanged("filetype");
					this.OnfiletypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoadedFile_LandingPagestaging", Storage="_LandingPagestagings", ThisKey="id", OtherKey="LoadedFile_id")]
		public EntitySet<LandingPagestaging> LandingPagestagings
		{
			get
			{
				return this._LandingPagestagings;
			}
			set
			{
				this._LandingPagestagings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LandingPagestagings(LandingPagestaging entity)
		{
			this.SendPropertyChanging();
			entity.LoadedFile = this;
		}
		
		private void detach_LandingPagestagings(LandingPagestaging entity)
		{
			this.SendPropertyChanging();
			entity.LoadedFile = null;
		}
	}
}
#pragma warning restore 1591
