#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExitPagesMVC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JPStarter")]
	public partial class LINQtoSQLexitpgDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStagingExitPage(StagingExitPage instance);
    partial void UpdateStagingExitPage(StagingExitPage instance);
    partial void DeleteStagingExitPage(StagingExitPage instance);
    #endregion
		
		public LINQtoSQLexitpgDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["JPStarterConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLexitpgDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLexitpgDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLexitpgDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLexitpgDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StagingExitPage> StagingExitPages
		{
			get
			{
				return this.GetTable<StagingExitPage>();
			}
		}
		
		public System.Data.Linq.Table<vw_FilesNotYetLoaded> vw_FilesNotYetLoadeds
		{
			get
			{
				return this.GetTable<vw_FilesNotYetLoaded>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="staging.ExitPages")]
	public partial class StagingExitPage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Page;
		
		private string _Exits;
		
		private string _PageViews;
		
		private string _ExitRate;
		
		private System.Nullable<int> _LoadedFile_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPageChanging(string value);
    partial void OnPageChanged();
    partial void OnExitsChanging(string value);
    partial void OnExitsChanged();
    partial void OnPageViewsChanging(string value);
    partial void OnPageViewsChanged();
    partial void OnExitRateChanging(string value);
    partial void OnExitRateChanged();
    partial void OnLoadedFile_idChanging(System.Nullable<int> value);
    partial void OnLoadedFile_idChanged();
    #endregion
		
		public StagingExitPage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Page", DbType="VarChar(8000)")]
		public string Page
		{
			get
			{
				return this._Page;
			}
			set
			{
				if ((this._Page != value))
				{
					this.OnPageChanging(value);
					this.SendPropertyChanging();
					this._Page = value;
					this.SendPropertyChanged("Page");
					this.OnPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exits", DbType="VarChar(3000)")]
		public string Exits
		{
			get
			{
				return this._Exits;
			}
			set
			{
				if ((this._Exits != value))
				{
					this.OnExitsChanging(value);
					this.SendPropertyChanging();
					this._Exits = value;
					this.SendPropertyChanged("Exits");
					this.OnExitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageViews", DbType="VarChar(3000)")]
		public string PageViews
		{
			get
			{
				return this._PageViews;
			}
			set
			{
				if ((this._PageViews != value))
				{
					this.OnPageViewsChanging(value);
					this.SendPropertyChanging();
					this._PageViews = value;
					this.SendPropertyChanged("PageViews");
					this.OnPageViewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExitRate", DbType="VarChar(3000)")]
		public string ExitRate
		{
			get
			{
				return this._ExitRate;
			}
			set
			{
				if ((this._ExitRate != value))
				{
					this.OnExitRateChanging(value);
					this.SendPropertyChanging();
					this._ExitRate = value;
					this.SendPropertyChanged("ExitRate");
					this.OnExitRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadedFile_id", DbType="Int")]
		public System.Nullable<int> LoadedFile_id
		{
			get
			{
				return this._LoadedFile_id;
			}
			set
			{
				if ((this._LoadedFile_id != value))
				{
					this.OnLoadedFile_idChanging(value);
					this.SendPropertyChanging();
					this._LoadedFile_id = value;
					this.SendPropertyChanged("LoadedFile_id");
					this.OnLoadedFile_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_FilesNotYetLoaded")]
	public partial class vw_FilesNotYetLoaded
	{
		
		private int _ID;
		
		private string _filename;
		
		private string _filetype;
		
		public vw_FilesNotYetLoaded()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="VarChar(1000)")]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this._filename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filetype", DbType="VarChar(255)")]
		public string filetype
		{
			get
			{
				return this._filetype;
			}
			set
			{
				if ((this._filetype != value))
				{
					this._filetype = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
