#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExitPagesMVC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JPStarter")]
	public partial class LINQtoSQLexitpgDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLoadedFile(LoadedFile instance);
    partial void UpdateLoadedFile(LoadedFile instance);
    partial void DeleteLoadedFile(LoadedFile instance);
    partial void InsertStagingExitPage(StagingExitPage instance);
    partial void UpdateStagingExitPage(StagingExitPage instance);
    partial void DeleteStagingExitPage(StagingExitPage instance);
    #endregion
		
		public LINQtoSQLexitpgDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["JPStarterConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLexitpgDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLexitpgDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLexitpgDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLexitpgDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LoadedFile> LoadedFiles
		{
			get
			{
				return this.GetTable<LoadedFile>();
			}
		}
		
		public System.Data.Linq.Table<StagingExitPage> StagingExitPages
		{
			get
			{
				return this.GetTable<StagingExitPage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoadedFiles")]
	public partial class LoadedFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _filename;
		
		private string _filetype;
		
		private EntitySet<StagingExitPage> _StagingExitPages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    partial void OnfiletypeChanging(string value);
    partial void OnfiletypeChanged();
    #endregion
		
		public LoadedFile()
		{
			this._StagingExitPages = new EntitySet<StagingExitPage>(new Action<StagingExitPage>(this.attach_StagingExitPages), new Action<StagingExitPage>(this.detach_StagingExitPages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="VarChar(1000)")]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this.OnfilenameChanging(value);
					this.SendPropertyChanging();
					this._filename = value;
					this.SendPropertyChanged("filename");
					this.OnfilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filetype", DbType="VarChar(255)")]
		public string filetype
		{
			get
			{
				return this._filetype;
			}
			set
			{
				if ((this._filetype != value))
				{
					this.OnfiletypeChanging(value);
					this.SendPropertyChanging();
					this._filetype = value;
					this.SendPropertyChanged("filetype");
					this.OnfiletypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoadedFile_ExitPage", Storage="_StagingExitPages", ThisKey="id", OtherKey="LoadedFile_id")]
		public EntitySet<StagingExitPage> StagingExitPages
		{
			get
			{
				return this._StagingExitPages;
			}
			set
			{
				this._StagingExitPages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StagingExitPages(StagingExitPage entity)
		{
			this.SendPropertyChanging();
			entity.LoadedFile = this;
		}
		
		private void detach_StagingExitPages(StagingExitPage entity)
		{
			this.SendPropertyChanging();
			entity.LoadedFile = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="staging.ExitPages")]
	public partial class StagingExitPage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Page;
		
		private string _Exits;
		
		private string _PageViews;
		
		private string _ExitRate;
		
		private System.Nullable<int> _LoadedFile_id;
		
		private EntityRef<LoadedFile> _LoadedFile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPageChanging(string value);
    partial void OnPageChanged();
    partial void OnExitsChanging(string value);
    partial void OnExitsChanged();
    partial void OnPageViewsChanging(string value);
    partial void OnPageViewsChanged();
    partial void OnExitRateChanging(string value);
    partial void OnExitRateChanged();
    partial void OnLoadedFile_idChanging(System.Nullable<int> value);
    partial void OnLoadedFile_idChanged();
    #endregion
		
		public StagingExitPage()
		{
			this._LoadedFile = default(EntityRef<LoadedFile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Page", DbType="VarChar(8000)")]
		public string Page
		{
			get
			{
				return this._Page;
			}
			set
			{
				if ((this._Page != value))
				{
					this.OnPageChanging(value);
					this.SendPropertyChanging();
					this._Page = value;
					this.SendPropertyChanged("Page");
					this.OnPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exits", DbType="VarChar(3000)")]
		public string Exits
		{
			get
			{
				return this._Exits;
			}
			set
			{
				if ((this._Exits != value))
				{
					this.OnExitsChanging(value);
					this.SendPropertyChanging();
					this._Exits = value;
					this.SendPropertyChanged("Exits");
					this.OnExitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageViews", DbType="VarChar(3000)")]
		public string PageViews
		{
			get
			{
				return this._PageViews;
			}
			set
			{
				if ((this._PageViews != value))
				{
					this.OnPageViewsChanging(value);
					this.SendPropertyChanging();
					this._PageViews = value;
					this.SendPropertyChanged("PageViews");
					this.OnPageViewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExitRate", DbType="VarChar(3000)")]
		public string ExitRate
		{
			get
			{
				return this._ExitRate;
			}
			set
			{
				if ((this._ExitRate != value))
				{
					this.OnExitRateChanging(value);
					this.SendPropertyChanging();
					this._ExitRate = value;
					this.SendPropertyChanged("ExitRate");
					this.OnExitRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadedFile_id", DbType="Int")]
		public System.Nullable<int> LoadedFile_id
		{
			get
			{
				return this._LoadedFile_id;
			}
			set
			{
				if ((this._LoadedFile_id != value))
				{
					if (this._LoadedFile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoadedFile_idChanging(value);
					this.SendPropertyChanging();
					this._LoadedFile_id = value;
					this.SendPropertyChanged("LoadedFile_id");
					this.OnLoadedFile_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoadedFile_ExitPage", Storage="_LoadedFile", ThisKey="LoadedFile_id", OtherKey="id", IsForeignKey=true)]
		public LoadedFile LoadedFile
		{
			get
			{
				return this._LoadedFile.Entity;
			}
			set
			{
				LoadedFile previousValue = this._LoadedFile.Entity;
				if (((previousValue != value) 
							|| (this._LoadedFile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoadedFile.Entity = null;
						previousValue.StagingExitPages.Remove(this);
					}
					this._LoadedFile.Entity = value;
					if ((value != null))
					{
						value.StagingExitPages.Add(this);
						this._LoadedFile_id = value.id;
					}
					else
					{
						this._LoadedFile_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoadedFile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
